### ISSUE TITLE
support for php 7.3

### ISSUE THREAD

**Issue by lorvent** [lukeraymonddowning/honey#15]
Hello,

is it mandatory to have php 7.4?

since laravel 8.x requires php 7.3, i only use it (infact there is a breaking change with my application when i php 7.4)

so any plans of supporting php 7.3?

thanks

**Comment by lukeraymonddowning** [comment]
Hello! It is mandatory to have 7.4, yes.

I understand that some sites are still on 7.3, but I personally find shorthand functions and type hinting to be too valuable to forgo. I'm going to close this issue, but thank you for opening it.

I know you likely are already aware of this, but the list of incompatibilities between 7.3 and 7.4 are quite small: https://www.php.net/manual/en/migration74.incompatible.php

**Comment by lorvent** [comment]
For me, biggest issue is with `join` syntax has changed.

I really love shorthands too, especially after using them in es6

anyways, i respect your decision :+1:
