### ISSUE TITLE
Symfony\Component\HttpKernel\Exception\HttpException You shall not pass!

### ISSUE THREAD

**Issue by ehsantalkhouncheh** [lukeraymonddowning/honey#24]
I got this error after add honey middlware on my route :

Route::group(['middleware' => 'honey'], function () {
    Route::get('/directdebit', function () {
        return view('directdebit');
    })->name('directdebit');
});

i use laravel 8 and livewire

**Comment by lukeraymonddowning** [comment]
Hurrah! That exception means that Honey is working. That is the default exception that gets thrown if a bot is detected. If you fill the form out too quickly or fill in the missing fields, it will fail.

**Comment by ehsantalkhouncheh** [comment]
The problem is i didn't fill form at all i got this error when i tried to visit the form

**Comment by lukeraymonddowning** [comment]
It looks like you've put the middleware on the GET route rather than the PUT or POST route that your form points to.

**Comment by zepphub** [comment]
I have the same problem but I think the middleware is in the right place

Route::post('/newsletter-subscription', [App\Http\Controllers\NewsletterSubscriptionController::class, 'store'] )->middleware(['honey', 'honey-recaptcha'])->name('newsletter-subscription');
