### ISSUE TITLE
argument 1 passed to Lukeraymonddowning\Honey\Views\Honey::__construct() must be an instance of Lukeraymonddowning\Honey\InputNameSelectors\InputNameSelector

### ISSUE THREAD

**Issue by elbouziani** [lukeraymonddowning/honey#26]
i have this error after inserting <x-honey/> tag inside my register form

**Comment by lukeraymonddowning** [comment]
Closing this for now. Please reopen if you are still facing this issue. It sounds like you might have an issue with your service container bindings.
