### ISSUE TITLE
Issue CANCELLED. System has PHP7.3 (though in the admin panel it indicated php7.4) -- incompatible with your PHP version, PHP      extensions

### ISSUE THREAD

**Issue by wi-wi** [lukeraymonddowning/honey#29]
[InvalidArgumentException]                                                                       
  Package lukeraymonddowning/honey has a PHP requirement incompatible with your PHP version, PHP   
  extensions and Composer version   

QQ:
On OS linux with PHP7.4  and Composer version 2.0.9
What **php extensions** does lukeraymonddowning/honey require?

**Comment by lukeraymonddowning** [comment]
Closing this as it seems you figured out the 7.4 minimum :-)
