### ISSUE TITLE
recaptcha theme color

### ISSUE THREAD

**Issue by bastinald** [lukeraymonddowning/honey#31]
any way to set the recaptcha theme color to dark?

**Comment by lukeraymonddowning** [comment]
I could be wrong but I do believe you can just do:

```blade
<x-honey-recaptcha data-theme="dark" />
```

because it just forwards the attributes in Blade :-)

**Comment by lukeraymonddowning** [comment]
I don't think so as of yet. Would be happy to accept a PR though. Seems like a simple addition.
