### ISSUE TITLE
Undefined array key "honey_time"

### ISSUE THREAD

**Issue by yanuarpmbd** [lukeraymonddowning/honey#40]
Hi,
I got some error when integrating with livewire.

`ErrorException
Undefined array key "honey_time"
http://127.0.0.1:8000/`

I'm following installation step with default config

```
<form wire:submit.prevent="store">
    @csrf
    <input type="text" class="block text-sm py-3 px-4" wire:model="text"/>
    <x-honey/>
    <button type="submit" class="py-3 w-64">Submit</button>
</form>
```
My routes

`Route::get('/form', \App\Http\Livewire\Form::class,)->middleware(['honey'])->name('form');`

What's wrong here?

**Comment by kiritokatklian** [comment]
Make sure to use the middleware on a POST route and not GET.

**Comment by yanuarpmbd** [comment]
Big thanks @kiritokatklian
